import json

import pandas as pd
import streamlit as st
import streamlit.components.v1 as components

from graph_utils import (
    get_neighbor_edges,
    get_node_by_id,
    get_node_names,
    graph_to_html,
    merge_graphs,
)
from llm_service import generate_concept_graph
from sample_data import get_sample_graph


st.set_page_config(
    page_title="AI Concept Graph Builder",
    page_icon="🧠",
    layout="wide",
)


def initialize_session_state():
    if "graph" not in st.session_state:
        st.session_state.graph = None

    if "last_error" not in st.session_state:
        st.session_state.last_error = None

    if "selected_node" not in st.session_state:
        st.session_state.selected_node = None


def graph_as_dict(graph):
    return graph.model_dump()


def display_graph_summary(graph):
    col1, col2, col3 = st.columns(3)
    col1.metric("Nodes", len(graph.nodes))
    col2.metric("Edges", len(graph.edges))
    col3.metric("Suggestions", len(graph.suggested_concepts))


def display_selected_node_panel(graph, selected_node):
    node = get_node_by_id(graph, selected_node)

    if node is None:
        st.warning("Selected node was not found in the graph.")
        return

    st.subheader(f"Concept: {node.id}")
    st.caption(f"Category: {node.category}")
    st.write(node.definition)

    neighbor_edges = get_neighbor_edges(graph, selected_node)

    if neighbor_edges:
        st.markdown("#### Connected relationships")

        rows = []
        for edge in neighbor_edges:
            rows.append(
                {
                    "Source": edge.source,
                    "Relation": edge.relation,
                    "Target": edge.target,
                    "Explanation": edge.explanation,
                }
            )

        st.dataframe(pd.DataFrame(rows), use_container_width=True)
    else:
        st.info("No connected relationships found for this node yet.")


initialize_session_state()

st.title("🧠 AI Concept Graph Builder")
st.write(
    "This Streamlit app uses Gemini structured output to turn AI or computer science "
    "concepts into an interactive concept graph."
)

st.info(
    "Educational note: this app is designed for exploratory learning. "
    "Because the graph is generated by an LLM, important technical details should be verified with reliable sources."
)

with st.sidebar:
    st.header("Settings")

    model_name = st.selectbox(
        "Gemini model",
        options=["gemini-2.5-flash"],
        index=0,
    )

    max_new_nodes = st.slider(
        "Maximum new nodes per generation",
        min_value=4,
        max_value=12,
        value=7,
        step=1,
    )

    temperature = st.slider(
        "Temperature",
        min_value=0.0,
        max_value=1.0,
        value=0.2,
        step=0.1,
        help="Lower values make the output more deterministic.",
    )

    st.divider()

    if st.button("Load demo graph"):
        st.session_state.graph = get_sample_graph()
        st.session_state.selected_node = st.session_state.graph.center
        st.session_state.last_error = None
        st.rerun()

    if st.button("Clear graph"):
        st.session_state.graph = None
        st.session_state.selected_node = None
        st.session_state.last_error = None
        st.rerun()

    st.divider()
    st.markdown(
        """
        **App workflow**

        1. Enter a concept  
        2. Generate structured JSON  
        3. Visualize graph  
        4. Select a node  
        5. Expand selected node  
        """
    )

concept = st.text_input(
    "Enter an AI/CS concept",
    value="Transformer",
    placeholder="Examples: Transformer, Autoencoder, CNN, Gradient Descent",
)

col_generate, col_demo = st.columns([1, 1])

with col_generate:
    generate_clicked = st.button("Generate concept graph", type="primary")

with col_demo:
    demo_clicked = st.button("Use demo graph instead")

if demo_clicked:
    st.session_state.graph = get_sample_graph()
    st.session_state.selected_node = st.session_state.graph.center
    st.session_state.last_error = None
    st.rerun()

if generate_clicked:
    if not concept.strip():
        st.warning("Please enter a concept.")
    else:
        existing_nodes = (
            get_node_names(st.session_state.graph)
            if st.session_state.graph is not None
            else []
        )

        with st.spinner("Calling Gemini and generating structured concept graph..."):
            try:
                new_graph = generate_concept_graph(
                    concept=concept.strip(),
                    existing_nodes=existing_nodes,
                    max_new_nodes=max_new_nodes,
                    temperature=temperature,
                    model_name=model_name,
                    mode="generate",
                )

                st.session_state.graph = merge_graphs(
                    st.session_state.graph,
                    new_graph,
                )

                st.session_state.selected_node = concept.strip()
                st.session_state.last_error = None
                st.success("Concept graph generated successfully.")
                st.rerun()

            except Exception as e:
                st.session_state.last_error = str(e)
                st.error("Gemini generation failed. You can load the demo graph instead.")
                with st.expander("Error details"):
                    st.code(str(e))

if st.session_state.last_error:
    with st.expander("Last error"):
        st.code(st.session_state.last_error)

graph = st.session_state.graph

if graph is None:
    st.markdown("### Start by generating a graph or loading the demo graph.")
    st.write(
        "Suggested first concept: **Transformer**. "
        "After the graph appears, select a node and click **Expand selected concept**."
    )

else:
    display_graph_summary(graph)

    node_names = get_node_names(graph)

    if st.session_state.selected_node not in node_names:
        st.session_state.selected_node = graph.center if graph.center in node_names else node_names[0]

    selected_node = st.selectbox(
        "Select a node to view its definition or expand it",
        options=node_names,
        index=node_names.index(st.session_state.selected_node),
    )

    st.session_state.selected_node = selected_node

    graph_html = graph_to_html(graph, selected_node=selected_node)
    components.html(graph_html, height=680, scrolling=True)

    left_col, right_col = st.columns([1, 1])

    with left_col:
        display_selected_node_panel(graph, selected_node)

        if st.button("Expand selected concept", type="primary"):
            existing_nodes = get_node_names(graph)

            with st.spinner(f"Expanding concept: {selected_node}"):
                try:
                    expanded_graph = generate_concept_graph(
                        concept=selected_node,
                        existing_nodes=existing_nodes,
                        max_new_nodes=max_new_nodes,
                        temperature=temperature,
                        model_name=model_name,
                        mode="expand",
                    )

                    st.session_state.graph = merge_graphs(graph, expanded_graph)
                    st.session_state.last_error = None
                    st.success(f"Expanded: {selected_node}")
                    st.rerun()

                except Exception as e:
                    st.session_state.last_error = str(e)
                    st.error("Expansion failed. Please try again.")
                    with st.expander("Error details"):
                        st.code(str(e))

    with right_col:
        st.subheader("Suggested concepts")

        if graph.suggested_concepts:
            selected_suggestion = st.selectbox(
                "Choose a suggested concept to add",
                options=graph.suggested_concepts,
            )

            if st.button("Add selected suggested concept"):
                existing_nodes = get_node_names(graph)

                with st.spinner(f"Adding suggested concept: {selected_suggestion}"):
                    try:
                        suggestion_graph = generate_concept_graph(
                            concept=selected_suggestion,
                            existing_nodes=existing_nodes,
                            max_new_nodes=max_new_nodes,
                            temperature=temperature,
                            model_name=model_name,
                            mode="expand",
                        )

                        st.session_state.graph = merge_graphs(graph, suggestion_graph)
                        st.session_state.selected_node = selected_suggestion
                        st.session_state.last_error = None
                        st.success(f"Added: {selected_suggestion}")
                        st.rerun()

                    except Exception as e:
                        st.session_state.last_error = str(e)
                        st.error("Adding suggested concept failed.")
                        with st.expander("Error details"):
                            st.code(str(e))
        else:
            st.info("No suggested concepts available yet.")

        st.subheader("Download graph")

        graph_json = json.dumps(graph_as_dict(graph), indent=2)

        st.download_button(
            label="Download graph as JSON",
            data=graph_json,
            file_name="concept_graph.json",
            mime="application/json",
        )

    st.divider()

    with st.expander("View graph data tables"):
        st.markdown("#### Nodes")
        st.dataframe(
            pd.DataFrame([node.model_dump() for node in graph.nodes]),
            use_container_width=True,
        )

        st.markdown("#### Edges")
        st.dataframe(
            pd.DataFrame([edge.model_dump() for edge in graph.edges]),
            use_container_width=True,
        )